name: C_C++_CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        cmake_version: [3.20.4]
        gcc_version: [9]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - uses: lukka/get-cmake@v3.20.1
      - name: Get dependencies
        env:
          cmake_version: ${{ matrix.cmake_version }}
          gcc_version: ${{ matrix.gcc_version }}
        uses: NWChemEx-Project/.github/actions/get_dependencies@master
        with:
          dependencies: gcc gcovr openblas cblas lapacke scalapack boost eigen3 openmpi
      - name: cache-libint
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            libint-2.6.0/
            build/
          key: libint-gcc${{ matrix.gcc_version }}
      - name: build-libint
        env:
          cmake_version: ${{ matrix.cmake_version }}
          gcc_version: ${{ matrix.gcc_version }}
          CPP_GITHUB_TOKEN: ${{ secrets.CPP_GITHUB_TOKEN }}
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          export INSTALL_PATH=`pwd`/build
          # check code out
          wget https://github.com/evaleev/libint/releases/download/v2.6.0/libint-2.6.0.tgz
          tar -zxf libint-2.6.0.tgz
          cd libint-2.6.0
          export CXX=`which g++`
          export CC=`which gcc`
          cmake -H. -Bbuild -DCMAKE_INSTALL_PREFIX=${INSTALL_PATH} -DCMAKE_CXX_COMPILER=${CXX} -DCMAKE_C_COMPILER=${CC} -DCMAKE_CXX_FLAGS="-std=c++17" -DBUILD_SHARED_LIBS=ON -DCPP_GITHUB_TOKEN=$CPP_GITHUB_TOKEN
          cd build
          make
          make install
          # .github/workflows/scripts/build_and_test.sh
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
      - name: post cache check
        run: |
          # .github/workflows/scripts/build_and_test.sh
          ls
