name: Build and Deploy Documentation
on:
  push:
    branches:
      - master

jobs:
  Build-Documentation:
    uses: NWChemEx-Project/.github/.github/workflows/deploy_docs_tmpl.yaml@master
    with:
      target: integrals_cxx_api
      dependencies: cmake doxygen sphinx ninja gcc gcovr openblas cblas lapacke scalapack boost eigen3 openmpi libint
      generate_modules_docs: true
    secrets:
      CMAIZE_GITHUB_TOKEN: ${{ secrets.CMAIZE_GITHUB_TOKEN }}
